FROM jupyter/scipy-notebook

RUN python -m pip install rpyc

RUN python -m pip install octave_kernel

USER root

RUN apt-get -y update \
 && apt-get -y install \
    libcurl4-openssl-dev \
    gnuplot octave liboctave-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 18812

CMD ["/opt/conda/bin/rpyc_classic.py", "--host", "0.0.0.0"]

USER $NB_UID
