version: '3'

services:

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile_jupyter
    expose:
      - "18812"
    volumes:
      - ./workspace:/home/jovyan/workspace
    deploy:
      mode: replicated
      replicas: 5
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    volumes:
      - ./log:/root/log
      - ./workspace:/root/workspace
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
